apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  js.conf: |
    gzip                      on;
    gzip_http_version         1.1;
    gzip_disable              "msie6";
    gzip_vary                 on;
    gzip_min_length           1100;
    gzip_buffers              64 8k;
    gzip_comp_level           3;
    gzip_proxied              any;
    gzip_types                text/plain text/css application/x-javascript text/xml application/xml;

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html index.htm;

        location / {
            try_files $uri $uri/ /index.html;
            gzip on;
            gzip_static on;
            add_header Cache-Control "max-age=300";
            add_header Last-Modified "";
            add_header ETag "";
        }

        location ~* \.(css|js)$ {
            try_files $uri =404;
            access_log off;
            gzip on;
            gzip_static on;
            add_header Cache-Control "max-age=3600";
            add_header Last-Modified "";
            add_header ETag "";
        }
    }
