apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 8000;
        multi_accept on;
    }

    http {
        include       /etc/nginx/mime.types;
        types {
            application/json                      json;
            image/png                             png;
        }
        default_type  application/octet-stream;

        log_format compression '$remote_addr - $remote_user [$time_local] '
            '"$request" $status $upstream_addr '
            '"$http_referer" "$http_user_agent"';

        gzip                      on;
        gzip_http_version         1.1;
        gzip_disable              "msie6";
        gzip_vary                 on;
        gzip_min_length           1100;
        gzip_buffers              64 8k;
        gzip_comp_level           3;
        gzip_proxied              any;
        gzip_types                text/plain text/css application/x-javascript text/xml application/xml;

        server {
            listen 80;
            server_name localhost;

            root /usr/share/nginx/html;
            index index.html index.htm;

            location / {
                try_files $uri $uri/ /index.html;
                gzip on;
                gzip_static on;
                add_header Cache-Control "max-age=300";
                add_header Last-Modified "";
                add_header ETag "";
            }

            location ~* \.(css|js)$ {
                try_files $uri =404;
                access_log off;
                gzip on;
                gzip_static on;
                add_header Cache-Control "max-age=3600";
                add_header Last-Modified "";
                add_header ETag "";
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: react-config
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: react-config
        configMap:
          name: react-config
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: ${NODE_PORT}
  type: NodePort