apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: react
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: ${AND_DOCKER_REGISTRY_NAME}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: react-config
        - mountPath: /etc/nginx/conf.d/
          name: nginx-config
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      volumes:
      - name: react-config
        configMap:
          name: react-config
          defaultMode: 420
      - name: nginx-config
        configMap:
          name: nginx-config
          defaultMode: 420

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: ${NODE_PORT}
  type: NodePort
  